version: '3.7'
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
    - 3306:3306
    networks: 
      - inception_network
    volumes:
    - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

  nginx:
      build: requirements/nginx
      container_name: nginx
      depends_on:  
        - wordpress
      ports:
        - 443:443
      volumes: 
       - wordpress-data:/var/www/html/wordpress
      networks: 
        - inception_network
      restart: unless-stopped

  wordpress:
      build: requirements/wordpress
      container_name: wordpress
      depends_on:  
        - mariadb
      env_file:
          - .env
      ports:
        - 9000:9000 
      volumes: 
       - wordpress-data:/var/www/html/wordpress
      networks: 
        - inception_network
      restart: always
  
  adminer:
    build: requirements/bonus/adminer/
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    depends_on:
      - nginx
    networks:
      - inception_network
    restart: always

  phpmyadmin:
    build: requirements/bonus/phpmyadmin/
    container_name: phpmyadmin
    depends_on:
      - redis
    ports:
      - 8081:8081
    networks:
      - inception_network
    restart: always

  ftp:
    build: requirements/bonus/ftp/
    container_name: ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes: 
     - wordpress-data:/var/www/html/wordpress  
    env_file:
      - .env
    restart: always
    networks:
      - inception_network

  redis:
    build: requirements/bonus/redis
    container_name: redis
    depends_on:
      - nginx
    ports:
      - "6379:6379"
    networks:
      - inception_network
    restart: always
    env_file:
      - .env

  website:
    container_name: site
    build: requirements/bonus/site/
    image: site
    networks:
      - inception_network
    ports:
      - "1234:1234"
    restart: always
    env_file:
      - .env
  
networks:
  inception_network:

volumes:
  mariadb-data:
    driver_opts:
      type: none
      device: /home/oronda/data/mysql
      o: bind
  wordpress-data:
    driver_opts:
      type: none
      device: /home/oronda/data/html/wordpress
      o: bind
  